int _putchar(char);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
void _puts(char *str);
void print_rev(char *s);
void puts2(char *str);
void rev_string(char *s);
int string_length(char*);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
